sonar.projectKey=meredyk48_spliit
sonar.organization=meredyk48

# Caminho do código fonte
sonar.sources=src

# Arquivos a excluir
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/public/**

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json